services:
  bot:
    build: .
    container_name: "gmail_telegram_bot"
    restart: always
    env_file:
      - ./.env
    ports:
      - 2020:2020
    networks:
      - core-net
    volumes:
      - ./log.txt:/app/log.txt

networks:
  core-net:
    external: true
